---
title: "Hartford 911 Calls"
output: 
  html_notebook:
    code_folding: hide
date: "2026-07-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("suncalc")
#install.packages("lutz")
library(tidyverse)
library(mosaic)
library(data.table)
library(lubridate)
library(suncalc)
library(lutz)
```

```{r, include=FALSE}
# Searches for files in the folder 

vfiles <- list.files("../Data/raw/Hartford/crimes", full.names = TRUE) 

getwd()
# Empty list 

dfcalls_list <- vector("list", length(vfiles)) 

# Reads each file and appends it to a list (which is efficient) 

for(X in seq_along(vfiles)){

  dftemp <- fread(vfiles[X], check.names = TRUE) %>% 
   rename_all(tolower) %>% 
    mutate_all(as.character) %>% 
    select(-starts_with("v")) 
  
  if(grepl("Weekly", vfiles[X])){ 
    dftemp <- dftemp %>% 
      rename(dateend = date) 
  } 
  dfcalls_list[[X]] <- dftemp 
} 


rm(dftemp, X, vfiles); gc() 

dfcalls_list <- bind_rows(dfcalls_list) 

rm(dftemp, X, vfiles); gc() 

#Bind all the elements of the list into a single data frame. 

calls <- bind_rows(dfcalls_list) 

names(calls)

calls <- calls %>%
  mutate(
    time_clean = coalesce(time_24hr, time),
    date_clean = coalesce(date, date1),
    code_clean = coalesce(code_2, code2)
  ) %>% 
  select(-c(date, date1,code_2,code2))
```





```{r,include=FALSE}
calls %>%
  mutate(yr = year(as.Date(substr(date_clean, 1, 10), format = "%Y/%m/%d"))) %>%
  filter(yr %in% c(2020, 2021, 2022, 2023)) %>%
  group_by(yr) %>%
  summarize(
    n = n(),
    pct_na_timeclean = mean(is.na(time_clean) | time_clean == ""),
    pct_na_initiator = mean(is.na(call_initiated_by) | call_initiated_by == "")
  )
```

```{r,include=FALSE}
calls %>%
  mutate(date_parsed = as.Date(substr(date_clean, 1, 10), format = "%Y/%m/%d")) %>%
  filter(lubridate::year(date_parsed) %in% c(2022, 2023)) %>%
  count(call_initiated_by) %>%
  arrange(desc(n))
```


```{r}
as_tibble(calls) %>%
  count(`priority`, sort = TRUE) %>%
  print(n = 100)
```


```{r}
# Call Type Classification

        
calls_sorted <- calls %>%
  mutate(  
    priority = case_when(
      priority == "A" ~ "Priority 1",
      priority == "B" ~ "Priority 2",
      priority == "C" ~ "Priority 3",
      TRUE ~ NA_character_
    ),
    priority_number = as.numeric(str_extract(priority, "\\d+")),
    description_final = coalesce(description_1, description_2, description1, description),
    calls_disorder = as.integer(`description_final` %in% c("BREACH OF PEACE", "NOISE COMPLAINT", "PROPERTY DAMAGE", "VICE OFFENSE (SPECIFY)", "THREATENING/HARASSMENT", "INTOXICATED PERSON", "GROUP DISTURBING")),
    calls_behavior = as.integer(`description_final` %in% c("SUSPICIOUS PERSON", "SUSPICIOUS VEHICLE", "LOITERING", "TRESPASSING")),
    calls_traffic = as.integer(`description_final` %in% c("ACCIDENT (MOTOR VEHICLE)", "ACCIDENT (M/V W/ INJURY)")),
    calls_gun = as.integer(`description_final` %in% c("SHOTS FIRED", "GUN INVOLVED")),
    
    calls_robbery = as.integer(`description_final` %in% c("MUGGING/STREET ROBBERY", "PURSE SNATCH")),
    calls_aggravated_assault = as.integer(`description_final` == "ASSAULT--SERIOUS"),
    calls_burglary = as.integer(`description_final` == "BREAKING AND ENTERING"),
    calls_theft = as.integer(`description_final` == "LARCENY"),
    calls_mv_theft = as.integer(`description_final` == "STOLEN VEHICLE"),
    
    calls_violent = calls_robbery + calls_aggravated_assault,
    calls_property = calls_burglary + calls_theft + calls_mv_theft,
    calls_index = calls_violent + calls_property,
    
    date = as.Date(substr(date_clean, 1, 10), format = "%Y/%m/%d"),
    year = year(date),
    month = lubridate::floor_date(date, "month"),
    day_of_week = lubridate::wday(date, week_start = 1),
    hour = as.integer(time_clean) %/% 100, 
    minute = as.integer(time_clean) %% 100, 
    initiator = case_when(
      `call_initiated_by` == "OFFICER" ~ "Officer",
      `call_initiated_by` %in% c("CITIZEN", "E911 CALL") ~ "Citizen",
      `call_initiated_by` == "" ~ "Not Available",
      TRUE ~ NA_character_)
    ) %>% 
  filter(!is.na(minute), !is.na(initiator), !is.na(hour), !is.na(day_of_week), !is.na(date), !is.na(month))
```

```{r}
by_day_prior <- calls_sorted %>%
      count(date, priority) %>%
      rename(day = date)
  
ggplot(by_day_prior, aes(day, n, color = priority, group = priority)) +
  geom_line(alpha = .7) +
  facet_wrap(~priority, scales = "free_y") +
  labs(title = "Hartford 911 Calls by Timeline and Priority", x = "Day", y = "Calls") 
```

```{r}
by_month_prior <- calls_sorted %>% 
      count(month, priority) 

  
ggplot(by_month_prior, aes(month, n, color = priority, group = priority)) +
  geom_line() +
  facet_wrap(~priority, scales = "free_y") +
  labs(title = "Hartford 911 Calls by Month and Priority", x = "Month", y = "Calls") 
```

```{r}

by_year_type_prior <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(year = year, priority) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(year = year, priority) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(year = year, priority) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(year = year, priority) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(year = year, priority) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(year = year, priority) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(year = year, priority) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(year = year, priority) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(year = year, priority) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(year = year, priority) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(year = year, priority) %>% mutate(type = "Property Crime")
)

  
ggplot(by_year_type_prior, aes(year, n, color = priority, group = priority)) +
 geom_line(linewidth = .8, alpha = .8) + 
  facet_wrap(~type, scales = "free_y", ncol(3)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Hartford 911 Calls by Year and Priority", x = "Year", y = "Calls") 

```

```{r}
by_day_week <- calls_sorted %>% count(day = day_of_week)

by_week_type_prior <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(day= day_of_week, priority) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(day = day_of_week, priority) %>% mutate(type = "Property Crime")
)

# fix the order of days 
  by_week_type$day <- factor(by_week_type$day, 
                            levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
  
  ggplot(by_week_type_prior, aes(day, n, color = priority, group = priority)) +
  geom_line() +
  facet_wrap(~type, scales = "free_y") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Hartford 911 Calls by Day of the Week, Type, and Priority", x = "Day", y = "Calls") 
  
  
```

```{r, fig.width = 20}

heatmap <- calls_sorted %>%
  group_by(priority) %>% 
  filter(!is.na(priority)) %>%
  count(day_of_week, hour, priority) %>%
  ungroup() %>%
  mutate(day_of_week = factor(day_of_week,
                              levels = 1:7,
                              labels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")))
  

heatmap_percent <- heatmap %>%
  mutate(percent = (n / sum(n)) * 100)
  

ggplot(heatmap_percent, aes(hour, day_of_week, fill = percent)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "magma") +
  scale_x_continuous(breaks = seq(0, 23, by = 4)) +
  facet_wrap(~priority, scales = "free") + 
  theme_minimal() +
   labs(title = "Hartford 911 Call Volume Heatmap by Day, Hour, and Priority", x = "Hour of Day", y = "Day of Week", fill = "Proportion of Calls") 
```



```{r, warning = FALSE}
df_dates <- expand.grid(year = 2005:2023, month = 1:12, day = 1:31) %>% 

  filter(complete.cases(ymd(paste(year, month, day)))) %>% 

  mutate(date = ymd(paste(year, month, day, sep = "-"))) %>% 

  arrange(date) 

#Get suntime data 


df_sun <- df_dates %>% 

  mutate(lat = 41.7637,  

         lon = -72.6851) %>% 

  getSunlightTimes(data = ., tz = "America/New_York", keep = c("dawn", "sunrise", "sunset", "dusk", "night")) %>% 

  rename_all(tolower) %>%
  mutate(
    dawn = hour(dawn) + minute(dawn) / 60,
    sunrise = hour(sunrise) + minute(sunrise) / 60,
    sunset = hour(sunset) + minute(sunset) / 60,
    dusk = hour(dusk) + minute(dusk) / 60,
    night = hour(night) + minute(night) / 60
  )

df_sun %>%
  filter(year(date) == 2023) %>%
  ggplot() +
    geom_area(aes(x = date, y = dusk), fill = "skyblue3") +  
    geom_area(aes(x = date, y = sunset), fill = "khaki1") +  
    geom_area(aes(x = date, y = sunrise), fill = "skyblue3") +  
    geom_area(aes(x = date, y = dawn), fill = "grey90") +  
      scale_y_continuous(breaks = seq(0, 23, 2), expand = c(0, 0)) +  
      scale_x_date(date_labels =  "%b", date_breaks = "1 month", expand = c(0,0)) + 
      coord_cartesian(ylim = c(0, 23)) +  
      labs(x = "Month of 2023", y = "Time of the day") +  
      theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        panel.background = element_rect(fill = "grey90"),   
        panel.grid = element_blank(),  
        panel.border = element_blank(),   
        rect = element_blank(),  
        axis.line = element_blank()
        )  


```

```{r, warning = FALSE}
plottheme <- theme( 
  axis.text.x = element_text(size = 15), 
  axis.text.y = element_text(size = 15), 
  axis.title.x = element_text(size = 20), 
  axis.title.y = element_text(size = 20), 
  strip.text.x = element_text(size = 12), 
  strip.background = element_rect(fill = "grey85", color = "black"), 
  panel.background = element_blank(),  
  axis.line = element_line(colour = "black"), 
  legend.key = element_rect(colour = "transparent", fill = "transparent"), 
  legend.key.width = unit(2, "cm"), 
  legend.text = element_text(size = 20), 
  legend.title = element_text(size = 20), 
  legend.position = "none", 
  rect = element_rect(fill = "transparent")
  )


dst_dates <- tibble(
  year = 2005:2023,
  dst_spring = as.Date(c("2005-04-03", "2006-04-02", "2007-03-11","2008-03-09", "2009-03-08","2010-03-14", "2011-03-13", "2012-03-11", "2013-03-10", "2014-03-09", "2015-03-08", "2016-03-13", "2017-03-12", "2018-03-11", "2019-03-10", "2020-03-08", "2021-03-14", "2022-03-13", "2023-03-11")),
  dst_fall = as.Date(c("2005-10-30", "2006-10-29", "2007-11-04", "2008-11-02", "2009-11-01", "2010-11-07", "2011-11-06", "2012-11-04",
    "2013-11-03", "2014-11-02", "2015-11-01", "2016-11-06", "2017-11-05", "2018-11-04", "2019-11-03", "2020-11-01", "2021-11-07", "2022-11-06", "2023-11-05"))
)

calls_night <- calls_sorted %>%
  mutate(
    date = as.Date(date),
    hour_dec = hour + (minute / 60)
  ) %>%
  left_join(df_sun, by = "date") %>%
  filter(hour_dec >= sunset & hour_dec < night)

calls_sorted_night <- calls_night %>%
  group_by(date) %>%
  summarise(
    across(starts_with("calls_"), \(x) sum(x, na.rm = TRUE)),
    calls_average_priority = mean(priority_number, na.rm = TRUE)
  ) %>%
  ungroup()

dst_rd_spring <- calls_sorted_night %>%
  mutate( 
    year = year(date)
    ) %>%
  left_join(dst_dates, by = "year") %>%
  mutate(days_until_spring = as.integer(date - dst_spring)) %>%
  filter(days_until_spring %in% -21:21) %>%
  mutate(
    dst_on = if_else(days_until_spring >= 0, "yes", "no")
  ) %>%
  group_by(days_until_spring, dst_on) %>%
  summarise(
    across(starts_with("calls_"), \(x) mean(x, na.rm = TRUE)),
    calls_average_priority = mean(calls_average_priority, na.rm = TRUE)
  ) %>%
  ungroup()

vnames <- dst_rd_spring %>% select(starts_with("calls_")) %>% names()


for(X in vnames){ 

  f1 <- as.formula(paste0(X, "~ poly(days_until_spring, 2)")) 
  sub_no  <- dst_rd_spring %>% filter(dst_on == "no")
  sub_yes <- dst_rd_spring %>% filter(dst_on == "yes")

  if(length(unique(sub_no$days_until_spring)) < 3 | length(unique(sub_yes$days_until_spring)) < 3) next

  lm1 <- lm(f1, data = sub_no)
  lm2 <- lm(f1, data = sub_yes)
  pred1 <- predict(lm1, newdata = sub_no, se = TRUE)
  pred2 <- predict(lm2, newdata = sub_yes, se = TRUE)

  dst_rd_spring_plot <- bind_rows(sub_no, sub_yes) %>%
    mutate(pred = c(pred1$fit, pred2$fit), 
           upper = c(pred1$fit, pred2$fit) - qnorm(0.975)*c(pred1$se.fit, pred2$se.fit), 
           lower = c(pred1$fit, pred2$fit) + qnorm(0.975)*c(pred1$se.fit, pred2$se.fit)) 

  clean_title <- X %>% 
    str_replace("calls_", "") %>% 
    str_replace("_", " ") %>% 
    str_to_title()
  
  ylabel <- ifelse(str_detect(X, "clearedrate"), "Clearance rate", "Crimes") 
  
p <- ggplot(dst_rd_spring_plot, aes(x = days_until_spring, y = .data[[X]])) + 
    geom_point(aes(group = dst_on), size = 3, color = "royalblue", shape = 1) + 
    geom_line(aes(y = pred, group = dst_on)) + 
    geom_line(aes(y = upper, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_line(aes(y = lower, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_vline(xintercept = -0.5, linetype = "dashed", linewidth = 0.5) +  
    labs(title = paste("Hartford 911 RD:", clean_title), 
         x = "Days until Spring DST starts", 
         y = ylabel)
print(p)
}

```

```{r, warning = FALSE}
plottheme <- theme( 
  axis.text.x = element_text(size = 15), 
  axis.text.y = element_text(size = 15), 
  axis.title.x = element_text(size = 20), 
  axis.title.y = element_text(size = 20), 
  strip.text.x = element_text(size = 12), 
  strip.background = element_rect(fill = "grey85", color = "black"), 
  panel.background = element_blank(),  
  axis.line = element_line(colour = "black"), 
  legend.key = element_rect(colour = "transparent", fill = "transparent"), 
  legend.key.width = unit(2, "cm"), 
  legend.text = element_text(size = 20), 
  legend.title = element_text(size = 20), 
  legend.position = "none", 
  rect = element_rect(fill = "transparent")
  )


dst_dates <- tibble(
  year = 2005:2023,
  dst_spring = as.Date(c("2005-04-03", "2006-04-02", "2007-03-11","2008-03-09", "2009-03-08","2010-03-14", "2011-03-13", "2012-03-11", "2013-03-10", "2014-03-09", "2015-03-08", "2016-03-13", "2017-03-12", "2018-03-11", "2019-03-10", "2020-03-08", "2021-03-14", "2022-03-13", "2023-03-11")),
  dst_fall = as.Date(c("2005-10-30", "2006-10-29", "2007-11-04", "2008-11-02", "2009-11-01", "2010-11-07", "2011-11-06", "2012-11-04",
    "2013-11-03", "2014-11-02", "2015-11-01", "2016-11-06", "2017-11-05", "2018-11-04", "2019-11-03", "2020-11-01", "2021-11-07", "2022-11-06", "2023-11-05"))
)

calls_night <- calls_sorted %>%
  mutate(
    date = as.Date(date),
    hour_dec = hour + (minute / 60)
  ) %>%
  left_join(df_sun, by = "date") %>%
  filter(hour_dec >= sunset & hour_dec < night)

calls_sorted_night <- calls_night %>%
  group_by(date) %>%
  summarise(
    across(starts_with("calls_"), \(x) sum(x, na.rm = TRUE)),
    calls_average_priority = mean(priority_number, na.rm = TRUE)
  ) %>%
  ungroup()

dst_rd_fall <- calls_sorted_night %>%
  mutate( 
    year = year(date)
    ) %>%
  left_join(dst_dates, by = "year") %>%
  mutate(days_until_fall = as.integer(date - dst_fall)) %>%
  filter(days_until_fall %in% -21:21) %>%
  mutate(
    dst_on = if_else(days_until_fall >= 0, "yes", "no")
  ) %>%
  group_by(days_until_fall, dst_on) %>%
  summarise(
    across(starts_with("calls_"), \(x) mean(x, na.rm = TRUE)),
    calls_average_priority = mean(calls_average_priority, na.rm = TRUE)
  ) %>%
  ungroup()

vnames <- dst_rd_fall %>% select(starts_with("calls_")) %>% names()


for(X in vnames){ 

  f1 <- as.formula(paste0(X, "~ poly(days_until_fall, 2)")) 
  sub_no  <- dst_rd_fall %>% filter(dst_on == "no")
  sub_yes <- dst_rd_fall %>% filter(dst_on == "yes")

  if(length(unique(sub_no$days_until_fall)) < 3 | length(unique(sub_yes$days_until_fall)) < 3) next

  lm1 <- lm(f1, data = sub_no)
  lm2 <- lm(f1, data = sub_yes)
  pred1 <- predict(lm1, newdata = sub_no, se = TRUE)
  pred2 <- predict(lm2, newdata = sub_yes, se = TRUE)

  dst_rd_fall_plot <- bind_rows(sub_no, sub_yes) %>%
    mutate(pred = c(pred1$fit, pred2$fit), 
           upper = c(pred1$fit, pred2$fit) - qnorm(0.975)*c(pred1$se.fit, pred2$se.fit), 
           lower = c(pred1$fit, pred2$fit) + qnorm(0.975)*c(pred1$se.fit, pred2$se.fit)) 

  clean_title <- X %>% 
    str_replace("calls_", "") %>% 
    str_replace("_", " ") %>% 
    str_to_title()
  
  ylabel <- ifelse(str_detect(X, "clearedrate"), "Clearance rate", "Crimes") 
  
p <- ggplot(dst_rd_fall_plot, aes(x = days_until_fall, y = .data[[X]])) + 
    geom_point(aes(group = dst_on), size = 3, color = "royalblue", shape = 1) + 
    geom_line(aes(y = pred, group = dst_on)) + 
    geom_line(aes(y = upper, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_line(aes(y = lower, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_vline(xintercept = -0.5, linetype = "dashed", linewidth = 0.5) +  
    labs(title = paste("Hartford 911 RD:", clean_title), 
         x = "Days until Fall DST starts", 
         y = ylabel)
print(p)
}
```


