---
title: "San Francisco Descriptive + RD"
output: 
  html_notebook:
    code_folding: hide
  
date: "2026-05-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("suncalc")
#install.packages("lutz")
#install.packages("R.utils")
library(tidyverse)
library(mosaic)
library(data.table)
library(lubridate)
library(suncalc)
library(lutz)
```


```{r, include = FALSE}

vfiles <- list.files("../Data/raw/San_Francisco/OneDrive_1_8-2-2026", pattern = "\\.csv\\.gz$", full.names = TRUE)
dfcalls_list <- vector("list", length(vfiles))


columns_selected <- c(
  "pd_incident_report" ,
  "received_datetime" ,
  "onscene_datetime",
  "close_datetime",
  "call_type_original",
  "call_type_original_desc" ,
  "priority_original",
  "disposition",
  "onview_flag"
)

for (X in seq_along(vfiles)) {
  dftemp <- fread(vfiles[X], select = columns_selected, check.names = TRUE) %>% 
    rename_all(tolower) %>% 
    mutate_all(as.character) %>% 
    select(-starts_with("v"))
  
  if (grepl("Weekly", vfiles[X])) {
    dftemp <- dftemp %>% rename(dateend = date)
  }
  
  dfcalls_list[[X]] <- dftemp
}

calls <- bind_rows(dfcalls_list)
rm(dftemp, X, vfiles, dfcalls_list, columns_selected); gc()

```



```{r, include=TRUE}
as_tibble(calls) %>%
  count(`call_type_original_desc`, sort = TRUE) %>%
  filter(n > 1000) %>%
  print(n = 250)

as_tibble(calls) %>%
  count(`priority_original`, sort = TRUE) %>%
  print(n = 100)

as_tibble(calls) %>%
  count(`disposition`, sort = TRUE) %>%
  print(n = 100)

as_tibble(calls) %>%
  count(`onview_flag`, sort = TRUE) %>%
  print(n = 100)
```


```{r, include = FALSE}
library(lubridate)

calls <- calls %>% 
  rename(
    response_datetime = received_datetime,
    arrived_datetime  = onscene_datetime,
    closed_datetime   = close_datetime
  )


calls <- calls %>%
  mutate(
response_dt_parsed = parse_date_time(
    response_datetime, orders = c("mdY IMS p", "Ymd IMS p", "Ymd HMS", "mdY IM p", "mdy HMS p")),
arrived_dt_parsed = parse_date_time(
    arrived_datetime, orders = c("Ymd IMS p", "Ymd IMS p", "Ymd HMS", "mdY IM p", "mdy HMS p")),
closed_dt_parsed = parse_date_time(
    closed_datetime, orders = c("Ymd IMS p", "Ymd IMS p", "Ymd HMS", "mdY IM p", "mdy HMS p")),



    # Extract clean Dates (YYYY-MM-DD)
    response_date = as.Date(response_dt_parsed),
    arrived_date  = as.Date(arrived_dt_parsed),
    closed_date   = as.Date(closed_dt_parsed),
    
    # Extract clean 24-hour Times (HH:MM:SS)
    response_time = format(response_dt_parsed, "%H:%M:%S"),
    arrived_time  = format(arrived_dt_parsed,  "%H:%M:%S"),
    closed_time   = format(closed_dt_parsed,   "%H:%M:%S")
  ) 

```


```{r}
calls_sorted <- calls %>%
  mutate( 
    disposition = case_when(
       `disposition` %in% c("HAN", "GOA", "CIT", "ADV", "REP", "UTL", "NOM", "ND", "PAS", "CAN", "NCR", "ARR", "ABA") ~ `disposition`,
      TRUE ~ NA_character_),
    disposition_clean = str_trim(toupper(disposition)),
      calls_disposition_handled = as.integer(disposition_clean == "HAN"),
      calls_disposition_gone_on_arrival = as.integer(disposition_clean ==  "GOA"),
      calls_disposition_cited = as.integer(disposition_clean == "CIT"),
      calls_disposition_advised = as.integer(disposition_clean == "ADV"),
      calls_disposition_report = as.integer(disposition_clean == "REP"),
      calls_disposition_unable_to_locate = as.integer(disposition_clean ==  "UTL"),
      calls_disposition_no_merit = as.integer(disposition_clean ==  "NOM"),
      calls_disposition_no_disposition = as.integer(disposition_clean ==  "ND"),
      calls_disposition_premise_secure = as.integer(disposition_clean ==  "PAS"),
      calls_disposition_cancel = as.integer(disposition_clean ==  "CAN"),
      calls_disposition_noncriminal = as.integer(disposition_clean ==  "NCR"),
       calls_disposition_arrest = as.integer(disposition_clean ==  "ARR"),
       calls_disposition_abated = as.integer(disposition_clean ==  "ABA"),
  
     priority = `priority_original`,
    priority = case_when(
      priority == "A" ~ "Priority 1",
      priority == "B" ~ "Priority 2",
      priority == "C" ~ "Priority 3",
      TRUE ~ NA_character_
    ),
    type_clean = str_trim(toupper(call_type_original_desc)),
   
    calls_disorder = as.integer(type_clean %in% c("VANDALISM DV", "PERSON DUMPING", "PROSTITUTE/SOLICITE", "JUVENILE DISTURBANCE", "GRAFFITI VANDALISM", "PERSON SCREAMING", "INDECENT EXPOSURE", "VANDALISM", "NOISE NUISANCE", "HOMELESS COMPLAINT")),
    calls_behavior = as.integer(type_clean %in% c("STALKING", "AGGR SOLICITING", "PROWLER", "PERSON W/GUN", "PERSON W/KNIFE", "THREATS / HARASSMENT", "SUSPICIOUS VEHICLE", "TRESPASSER", "SUSPICIOUS PERSON")),
    calls_traffic = as.integer(type_clean  %in% c("MVA+INJURIES", "AUTO VS PED", "INJURY VEH ACCIDENT", "VEH ACCIDENT")),
    calls_gun = as.integer(type_clean %in% c("SHOOTING", "SHOT SPOTTER", "SHOTS FIRED")),
        calls_robbery = as.integer(type_clean  %in% c("PURSE SNATCH", "ROBBERY", "STRONGARM ROBBERY")),
        calls_aggravated_assault = as.integer(type_clean  %in% c("FIGHT W/WEAPONS", "AGG ASSAULT / ADW", "ASSAULT / BATTERY DV")),
        calls_burglary = as.integer(type_clean  %in% c("PERSON BREAKING IN", "BURGLARY")),
        calls_theft = as.integer(type_clean  %in% c("STOLEN PROPERTY", "GRAND THEFT", "PETTY THEFT")),
        calls_mv_theft = as.integer(type_clean  == "STOLEN VEHICLE"),

            calls_violent = calls_robbery + calls_aggravated_assault,
            calls_property = calls_burglary + calls_theft + calls_mv_theft,
            calls_index = calls_violent + calls_property,
    
              initiator = case_when(
                `onview_flag` == "Y" ~ "Officer",
                `onview_flag` == "N" ~ "Citizen",
                TRUE ~ NA_character_
              ), 
    
    datetime = lubridate::parse_date_time(
  response_datetime, 
  orders = c("Ymd IMS p", "mdy IMS p", "mdy IM p", "ymd HMS", "mdy IM")
),
    date = as.Date(datetime),
    year = year(datetime),
    month = lubridate::floor_date(datetime, "month"),
    day_of_week = lubridate::wday(datetime, week_start = 1),
    hour = hour(datetime), 
    minute = minute(datetime)
    ) %>% 
    filter(!is.na(minute), !is.na(initiator), !is.na(hour), !is.na(day_of_week), !is.na(date), !is.na(month), !is.na(priority))
```


```{r, fig.width = 10}
#minute of hr
by_minute <- calls_sorted %>%
  count(minute = minute)

ggplot(by_minute, aes(minute, n)) +
  geom_line() + 
  scale_x_continuous(breaks = seq(0, 59, by = 3)) +
  labs(title = "San Francisco 911 Times by Minute of the Hour", x = "Minute", y = "Calls") +
  theme_minimal()
```

```{r, fig.width = 10}
by_minute <- calls_sorted %>%
  count(minute = minute, year)

ggplot(by_minute, aes(minute, n)) +
  geom_line() + 
  facet_wrap(~year, scale = "free_y") +
  scale_x_continuous(breaks = seq(0, 59, by = 10)) +
  labs(title = "San Francisco 911 Times by Minute of the Hour", x = "Minute", y = "Calls") +
  theme_minimal()
```

```{r, fig.width = 10}
by_minute_month <- calls_sorted %>%
  mutate(month_clean = lubridate::month(month, label = TRUE)) %>%
  count(month_clean, minute)

ggplot(by_minute_month, aes(minute, n)) +
  geom_line() + 
  facet_wrap(~month_clean, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 59, by = 15)) +
  labs(title = "San Francisco 911 Times by Minute of the Hour", x = "Minute", y = "Calls") +
  theme_minimal()
```


```{r, fig.width=10}
#hr of day

by_hour <- calls_sorted %>%
  count(hour = hour)

ggplot(by_hour, aes(hour, n)) +
  geom_line() + 
  scale_x_continuous(breaks = 0:24) +
  labs(title = "San Francisco 911 Times by Hour of the Day", x = "Hour", y = "Calls") +
  theme_minimal()

```

```{r, fig.width = 10}
#hr of day type
by_hour_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(hour = hour) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(hour = hour) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(hour = hour) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(hour = hour) %>% mutate(type = "Theft"),
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(hour = hour) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(hour = hour) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(hour = hour) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(hour = hour) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(hour = hour) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(hour = hour) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(hour = hour) %>% mutate(type = "Property Crime")
)

# graphed distribution of 911 times by hour
ggplot(by_hour_type, aes(hour, n, color = type)) +
  geom_line() + 
  facet_wrap(~type, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 24, by = 4)) +
  labs(title = "San Francisco 911 Times by Hour of the Day and Call Type", x = "Hour", y = "Calls")+
  theme_minimal()
```

```{r, fig.width = 10}
by_hour <- calls_sorted %>%
  count(hour, year)

ggplot(by_hour, aes(hour, n)) +
  geom_line() + 
  scale_x_continuous(breaks = seq(0, 24, by = 4)) +
  facet_wrap(~year, scales = "free_y") +
  labs(title = "San Francisco 911 Times by Hour of the Day", x = "Hour", y = "Calls") +
  theme_minimal()

```

```{r, fig.width = 10}
by_hour_month <- calls_sorted %>%
  mutate(month_clean = lubridate::month(month, label = TRUE)) %>%
  count(month_clean, hour)

ggplot(by_hour_month, aes(hour, n)) +
  geom_line() + 
  facet_wrap(~month_clean, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 24, by = 4)) +
  labs(title = "San Francisco 911 Times by Hour of the Day", x = "Hour", y = "Calls") +
  theme_minimal()
```


```{r, fig.width = 10}
#hr of day type initiator
by_hour_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Theft"),
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(hour = hour, initiator) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(hour = hour, initiator) %>% mutate(type = "Property Crime")
) %>%
  filter(initiator %in% c("Citizen", "Officer"))

# graphed distribution of 911 times by hour
by_hour_type_proportional <- by_hour_type %>%
  group_by(initiator, type) %>%
  mutate(proportional = n / sum(n)) %>%
  ungroup()

ggplot(by_hour_type_proportional, aes(hour, proportional, color = initiator, group = initiator)) +
  geom_line(alpha = .8) +
  geom_smooth(se = FALSE) +
  facet_wrap(~type, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 24, by = 3)) +
  labs(title = "San Francisco 911 Times by Hour of the Day, Call Type, and Initiator", x = "Hour", y = "Calls") + 
  theme_minimal()
```

```{r, fig.width= 10}
by_day_week <- calls_sorted %>% 
  count(day = day_of_week)


  
# graph of distribution of 911 times by hour
ggplot(by_day_week, aes(day, n, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "San Francisco 911 Calls by Day of the Week", x = "Day", y = "Calls") +
  theme_minimal()
```


```{r, fig.width = 10}
#day of week type

by_week_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(day = day_of_week) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(day = day_of_week) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(day = day_of_week) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(day = day_of_week) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(day = day_of_week) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(day = day_of_week) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(day = day_of_week) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(day = day_of_week) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(day = day_of_week) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(day = day_of_week) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(day = day_of_week) %>% mutate(type = "Property Crime")
)


  
  ggplot(by_week_type, aes(day, n, color = type, group = type)) +
  geom_line() +
  geom_point() +
  facet_wrap(~type, scales = "free_y") +
  labs(title = "San Francisco 911 Calls by Day of the Week and Type", x = "Day", y = "Calls") +
  theme_minimal()
```


```{r, fig.width = 10}
#day/year

by_date <- calls_sorted %>% 
  count(date = date)

ggplot(by_date, aes(date, n)) +
  geom_line(alpha = .7) + 
  scale_x_date(date_labels = "%b-%d-%y", date_breaks = "6 months") +
  labs(title = "San Francisco 911 Times by Day Timeline", x = "Date", y = "Calls") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) 
```

```{r, fig.width = 10}
#day/year type

by_day_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(day = date) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(day = date) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(day = date) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(day= date) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(day = date) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(day = date) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(day = date) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(day = date) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(day = date) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(day = date) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(day = date) %>% mutate(type = "Property Crime")
)

  
ggplot(by_day_type, aes(day, n, color = type, group = type)) +
  geom_line(alpha = .7) +
  geom_smooth(se = FALSE) +
  facet_wrap(~type, scales = "free_y") +
  labs(title = "San Francisco 911 Calls by Timeline and Type", x = "Day", y = "Calls") +
  theme_minimal() +
   theme(axis.text.x = element_text(angle = 45))
```

```{r, fig.width = 10}
#day/year type initiator
by_day_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(day = date, initiator) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(day = date, initiator) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(day = date, initiator) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(day= date, initiator) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(day = date, initiator) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(day = date, initiator) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(day = date, initiator) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(day = date, initiator) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(day = date, initiator) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(day = date, initiator) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(day = date, initiator) %>% mutate(type = "Property Crime")
) %>%
  filter(initiator %in% c("Citizen", "Officer"))

by_day_type_proportional <- by_day_type %>%
  group_by(initiator, type) %>%
  mutate(proportional = n / sum(n)) %>%
  ungroup()

ggplot(by_day_type_proportional, aes(day, proportional, color = initiator, group = initiator)) +
  geom_line(alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_wrap(~type, scales = "free_y") +
  labs(title = "San Francisco 911 Calls by Timeline, Type, and Initiator (Cleaned)", x = "Day", y = "Calls*") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45))
```

```{r, fig.width = 10}
#month/year
by_month <- calls_sorted %>% 
      count(month)
      
ggplot(by_month, aes(month, n)) +
  geom_line()  +
  labs(title = "San Francisco 911 Calls by Month", x = "Month", y = "Calls") +
    theme_minimal ()
```

```{r, fig.width = 10}
#month/year type

by_month_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(month = month) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(month = month) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(month = month) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(month = month) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(month = month) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(month = month) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(month = month) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(month = month) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(month = month) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(month = month) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(month = month) %>% mutate(type = "Property Crime")
)


ggplot(by_month_type, aes(month, n, color = type)) +
  geom_line(alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_wrap(~type, scales = "free_y") +
  labs(title = "San Francisco 911 Calls by Month and Type", x = "Month", y = "Calls*") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45))
```

```{r, fig.width = 10}
#month/year type initiator 


by_month_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(month = month, initiator) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(month = month, initiator) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(month = month, initiator) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(month = month, initiator) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(month = month, initiator) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(month = month, initiator) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(month = month, initiator) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(month = month, initiator) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(month = month, initiator) %>% mutate(type = "Gunshots"),
  calls_sorted %>% filter(calls_violent == 1) %>% count(month = month, initiator) %>% mutate(type = "Violent Crime"),
  calls_sorted %>% filter(calls_property == 1) %>% count(month = month, initiator) %>% mutate(type = "Property Crime")
) %>%
  filter(initiator %in% c("Citizen", "Officer"))

by_month_type_proportional <- by_month_type %>%
  group_by(initiator, type) %>%
  mutate(proportional = n / sum(n)) %>%
  ungroup()

ggplot(by_month_type_proportional, aes(month, proportional, color = initiator, group = initiator)) +
  geom_line(alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_wrap(~type, scales = "free_y") + 
  labs(title = "San Francisco 911 Calls by Month, Type, and Initiator (Cleaned)", x = "Month", y = "Calls*") +
  theme_minimal() +
    theme(axis.text.x = element_text(angle = 45))
```

```{r, fig.width = 10}


#time diff
time_differences <- calls_sorted %>%
  as_tibble() %>%
  mutate(
    time_arrive   = as.numeric(arrived_dt_parsed - response_dt_parsed) / 60,
    time_on_scene = as.numeric(closed_dt_parsed - arrived_dt_parsed) / 60,
    time_total    = as.numeric(closed_dt_parsed - response_dt_parsed) / 60
  )

time_differences_all <- bind_rows(
  time_differences %>%
    select(time_arrive, time_on_scene, time_total) %>%
    mutate(type = "All Calls")
)

time_differences_all %>%
  filter(time_arrive >= 0, time_arrive <= 120, time_on_scene >= 0, time_on_scene <= 120, time_total >= 0, time_total <= 120) %>%
  ggplot() +
    geom_histogram(aes(time_arrive, fill = "Time to Arrive"), color = "green", alpha = .4, binwidth = 5) +
    geom_histogram(aes(time_on_scene, fill = "Time on Scene"), color = "red", alpha = .4, binwidth = 5) +
    geom_histogram(aes(time_total, fill = "Total Time"), color = "blue", alpha = .4, binwidth = 5) +
  theme_minimal() +
  labs(title = "San Francisco 911 Call Time Differences", x = "Minutes", y = "Number of Calls", fill = "Time Difference")

```

```{r, fig.width = 10}
#time diff type 

time_differences_by_type <- bind_rows(
  time_differences %>% filter(calls_robbery == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Robbery"),
  time_differences %>% filter(calls_aggravated_assault == 1) %>% select(time_arrive, time_on_scene, time_total)%>% mutate(type = "Aggravated Assault"),
  time_differences %>% filter(calls_burglary == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Burglary"),
  time_differences %>% filter(calls_theft == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Theft"), 
  time_differences %>% filter(calls_mv_theft == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "MV Theft"),
  time_differences %>% filter(calls_disorder == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Disorder"),
  time_differences %>% filter(calls_behavior == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Susp/Unwanted"),
  time_differences %>% filter(calls_traffic == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Traffic"),
  time_differences %>% filter(calls_gun == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Gunshots"),
  time_differences %>% filter(calls_violent == 1) %>% select(time_arrive, time_on_scene, time_total)  %>% mutate(type = "Violent Crime"),
  time_differences %>% filter(calls_property == 1) %>% select(time_arrive, time_on_scene, time_total) %>% mutate(type = "Property Crime")
)

time_differences_by_type %>%
  filter(time_arrive >= 0, time_arrive <= 120,
         time_on_scene >= 0, time_on_scene <= 120,
         time_total >= 0, time_total <= 120) %>%
    ggplot() +
      geom_histogram(aes(time_arrive, fill = "Time to Arrive"), binwidth = 5, alpha = .4, color = "green") +
      geom_histogram(aes(time_on_scene, fill = "Time on Scene"), binwidth = 5, alpha = .4, color = "red") +
      geom_histogram(aes(time_total, fill = "Total Time"), binwidth = 5, alpha = .4, color = "blue") +
    facet_wrap(~type, scales = "free_y") + 
    theme_minimal() +
    labs(title = "San Francisco 911 Difference Between Response and Arrived Time by Type", x = "Minutes", y = "Number of Calls", fill = "Type")

```

```{r, fig.width = 10}
#heatmap percent 

heatmap_by_type <- bind_rows(
  calls_sorted %>% filter(calls_robbery == 1) %>% count(day_of_week, hour) %>% mutate(type = "Robbery"),
  calls_sorted %>% filter(calls_aggravated_assault == 1) %>% count(day_of_week, hour) %>% mutate(type = "Aggravated Assault"),
  calls_sorted %>% filter(calls_burglary == 1) %>% count(day_of_week, hour) %>% mutate(type = "Burglary"),
  calls_sorted %>% filter(calls_theft == 1) %>% count(day_of_week, hour) %>% mutate(type = "Theft"), 
  calls_sorted %>% filter(calls_mv_theft == 1) %>% count(day_of_week, hour) %>% mutate(type = "MV Theft"),
  calls_sorted %>% filter(calls_disorder == 1) %>% count(day_of_week, hour) %>% mutate(type = "Disorder"),
  calls_sorted %>% filter(calls_behavior == 1) %>% count(day_of_week, hour) %>% mutate(type = "Susp/Unwanted"),
  calls_sorted %>% filter(calls_traffic == 1) %>% count(day_of_week, hour) %>% mutate(type = "Traffic"),
  calls_sorted %>% filter(calls_gun == 1) %>% count(day_of_week, hour) %>% mutate(type = "Gunshots")
)


# By percent so we can see the smaller types

heatmap_by_type_percent <- heatmap_by_type %>%
  group_by(type) %>%
  mutate( percent = (n / sum(n)) * 100) %>%
  ungroup()

ggplot(heatmap_by_type_percent, aes(hour, day_of_week, fill = percent)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "magma") +
  scale_x_continuous(breaks = seq(0, 23, by = 4)) +
  facet_wrap(~type, scales = "free") +
  theme_minimal() +
   labs(title = "San Francisco 911 Call Volume Heatmap by Day and Hour", x = "Hour of Day", y = "Day of Week", fill = "% of Types Total") 
```

```{r, fig.width = 10}
#disposition day/year
disposition_labels <- c(
  "ABA" = "Abated",
  "ADV" = "Advised",
  "ARR" = "Arrest Made",
  "CAN" = "Cancelled",
  "CIT" = "Cited",
  "GOA" = "Gone on Arrival",
  "HAN" = "Handled",
  "NCR" = "Noncriminal",
  "ND"  = "No Disposition",
  "NOM" = "No Merit",
  "PAS" = "Premise Secure",
  "REP" = "Report Written",
  "UTL" = "Unable to Locate",
  "NA"  = "Not Classified"
)

by_day <- calls_sorted %>%
      count(date, disposition_clean) %>%
      rename(day = date)
  
ggplot(by_day, aes(day, n, color = disposition_clean, group = disposition_clean)) +
  geom_line(alpha = .7) +
  geom_smooth(se = FALSE) +
  scale_color_discrete(labels = disposition_labels) +
  facet_wrap(~disposition_clean, scales = "free_y", labeller = as_labeller(disposition_labels)) +
  labs(title = "San Francisco 911 Calls by Timeline and Disposition", x = "Day", y = "Calls") 

```

```{r, fig.width = 10}
#disposition month/year
disposition_labels <- c(
  "ABA" = "Abated",
  "ADV" = "Advised",
  "ARR" = "Arrest Made",
  "CAN" = "Cancelled",
  "CIT" = "Cited",
  "GOA" = "Gone on Arrival",
  "HAN" = "Handled",
  "NCR" = "Noncriminal",
  "ND"  = "No Disposition",
  "NOM" = "No Merit",
  "PAS" = "Premise Secure",
  "REP" = "Report Written",
  "UTL" = "Unable to Locate",
  "NA"  = "Not Classified"
)

by_month <- calls_sorted %>% 
      count(month, disposition_clean) 

  
ggplot(by_month, aes(month, n, color = disposition_clean, group = disposition_clean)) +
  geom_line() +
   geom_smooth(se = FALSE) +
   scale_color_discrete(labels = disposition_labels) +
  facet_wrap(~disposition_clean, scales = "free_y", labeller = as_labeller(disposition_labels)) +
  labs(title = "San Francisco 911 Calls by Month and Disposition", x = "Month", y = "Calls") 
```

```{r, fig.width = 10}
#disposition year/type
by_year <- calls_sorted 

disposition_labels <- c(
  "ABA" = "Abated",
  "ADV" = "Advised",
  "ARR" = "Arrest Made",
  "CAN" = "Cancelled",
  "CIT" = "Cited",
  "GOA" = "Gone on Arrival",
  "HAN" = "Handled",
  "NCR" = "Noncriminal",
  "ND"  = "No Disposition",
  "NOM" = "No Merit",
  "PAS" = "Premise Secure",
  "REP" = "Report Written",
  "UTL" = "Unable to Locate",
  "NA"  = "Not Classified"
)

by_year_type <- bind_rows(
  by_year %>% filter(calls_robbery == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Robbery"),
  by_year %>% filter(calls_aggravated_assault == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Aggravated Assault"),
  by_year %>% filter(calls_burglary == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Burglary"),
  by_year %>% filter(calls_theft == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Theft"), 
  by_year %>% filter(calls_mv_theft == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "MV Theft"),
  by_year %>% filter(calls_disorder == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Disorder"),
  by_year %>% filter(calls_behavior == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Susp/Unwanted"),
  by_year %>% filter(calls_traffic == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Traffic"),
  by_year %>% filter(calls_gun == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Gunshots"),
  by_year %>% filter(calls_violent == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Violent Crime"),
  by_year %>% filter(calls_property == 1) %>% count(year = year, disposition_clean) %>% mutate(type = "Property Crime")
)

  
ggplot(by_year_type, aes(year, n, color = disposition_clean, group = disposition_clean)) +
 geom_line(linewidth = .8, alpha = .8) + 
  scale_color_discrete(labels = disposition_labels) +
  facet_wrap(~type, scales = "free_y") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "San Francisco 911 Calls by Year and Disposition", x = "Year", y = "Calls") 

```

```{r, fig.width = 10}
#day/year priority
by_day_prior <- calls_sorted %>%
      count(response_date, priority) %>%
      rename(day = response_date)
  
ggplot(by_day_prior, aes(day, n, color = priority, group = priority)) +
  geom_line(alpha = .7) +
  facet_wrap(~priority, scales = "free_y") +
  labs(title = "San Francisco 911 Calls by Timeline and Priority", x = "Day", y = "Calls") 
```

```{r, fig.width = 10}
#month/year priority
by_month_prior <- calls_sorted %>% 
      count(month, priority) 

  
ggplot(by_month_prior, aes(month, n, color = priority, group = priority)) +
  geom_line() +
  facet_wrap(~priority, scales = "free_y") +
  labs(title = "San Francisco 911 Calls by Month and Priority", x = "Month", y = "Calls") 
```

```{r, fid.width = 10}
#year/type priority 
by_year <- calls_sorted 

by_year_type_prior <- bind_rows(
  by_year %>% filter(calls_robbery == 1) %>% count(year = year, priority) %>% mutate(type = "Robbery"),
  by_year %>% filter(calls_aggravated_assault == 1) %>% count(year = year, priority) %>% mutate(type = "Aggravated Assault"),
  by_year %>% filter(calls_burglary == 1) %>% count(year = year, priority) %>% mutate(type = "Burglary"),
  by_year %>% filter(calls_theft == 1) %>% count(year = year, priority) %>% mutate(type = "Theft"), 
  by_year %>% filter(calls_mv_theft == 1) %>% count(year = year, priority) %>% mutate(type = "MV Theft"),
  by_year %>% filter(calls_disorder == 1) %>% count(year = year, priority) %>% mutate(type = "Disorder"),
  by_year %>% filter(calls_behavior == 1) %>% count(year = year, priority) %>% mutate(type = "Susp/Unwanted"),
  by_year %>% filter(calls_traffic == 1) %>% count(year = year, priority) %>% mutate(type = "Traffic"),
  by_year %>% filter(calls_gun == 1) %>% count(year = year, priority) %>% mutate(type = "Gunshots"),
  by_year %>% filter(calls_violent == 1) %>% count(year = year, priority) %>% mutate(type = "Violent Crime"),
  by_year %>% filter(calls_property == 1) %>% count(year = year, priority) %>% mutate(type = "Property Crime")
)

  
ggplot(by_year_type_prior, aes(year, n, color = priority, group = priority)) +
 geom_line(linewidth = .8, alpha = .8) + 
  facet_wrap(~type, scales = "free_y") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "San Francisco 911 Calls by Year and Priority", x = "Year", y = "Calls") 

```

```{r, include=FALSE}
#sunlight data


df_dates <- expand.grid(year = 2015:2025, month = 1:12, day = 1:31) %>% 

  filter(complete.cases(ymd(paste(year, month, day)))) %>% 

  mutate(date = ymd(paste(year, month, day, sep = "-"))) %>% 

  arrange(date) 

 df_dates

#Get suntime data 


df_sun <- df_dates %>% 

  mutate(lat =  37.7749,  

         lon = -122.4194) %>% 

  getSunlightTimes(data = ., tz = "America/Los_Angeles", keep = c("dawn", "sunrise", "sunset", "dusk", "night")) %>% 

  rename_all(tolower) %>%
  mutate(
    dawn = hour(dawn) + minute(dawn) / 60,
    sunrise = hour(sunrise) + minute(sunrise) / 60,
    sunset = hour(sunset) + minute(sunset) / 60,
    dusk = hour(dusk) + minute(dusk) / 60,
    night = hour(night) + minute(night) / 60
  )

df_sun

```

```{r, fig.width = 10}
#sun graph
df_sun %>%
  filter(year(date) == 2024) %>%
  ggplot() +
    geom_area(aes(x = date, y = dusk), fill = "skyblue3") +  
    geom_area(aes(x = date, y = sunset), fill = "khaki1") +  
    geom_area(aes(x = date, y = sunrise), fill = "skyblue3") +  
    geom_area(aes(x = date, y = dawn), fill = "grey90") +  
      scale_y_continuous(breaks = seq(0, 23, 2), expand = c(0, 0)) +  
      scale_x_date(date_labels =  "%b", date_breaks = "1 month", expand = c(0,0)) + 
      coord_cartesian(ylim = c(0, 23)) +  
      labs(x = "Month of 2024", y = "Time of the day") +  
      theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        panel.background = element_rect(fill = "grey90"),   
        panel.grid = element_blank(),  
        panel.border = element_blank(),   
        rect = element_blank(),  
        axis.line = element_blank()
        )  

```

```{r, fig.width = 10}
#spring RD (change disposition from raw count of crimes to proportion)
plottheme <- theme( 
  axis.text.x = element_text(size = 15), 
  axis.text.y = element_text(size = 15), 
  axis.title.x = element_text(size = 20), 
  axis.title.y = element_text(size = 20), 
  strip.text.x = element_text(size = 12), 
  strip.background = element_rect(fill = "grey85", color = "black"), 
  panel.background = element_blank(),  
  axis.line = element_line(colour = "black"), 
  legend.key = element_rect(colour = "transparent", fill = "transparent"), 
  legend.key.width = unit(2, "cm"), 
  legend.text = element_text(size = 20), 
  legend.title = element_text(size = 20), 
  legend.position = "none", 
  rect = element_rect(fill = "transparent")
  )


dst_dates <- tibble(
  year = 2015:2025,
  dst_spring = as.Date(c("2015-03-08", "2016-03-13", "2017-03-12", "2018-03-11", "2019-03-10", "2020-03-08", "2021-03-14", "2022-03-13", "2023-03-12", "2024-03-10", "2025-03-09")),
  dst_fall = as.Date(c("2015-11-01", "2016-11-06", "2017-11-05", "2018-11-04", "2019-11-03", "2020-11-01", "2021-11-07", "2022-11-06", "2023-11-05", "2024-11-03", "2025-11-02"))
)


df_sun_clean <- df_sun %>% distinct(date, .keep_all = TRUE)

calls_night <- calls_sorted %>%
  mutate(
  hour_dec = as.numeric(substr(response_time, 1, 2)) + 
               as.numeric(substr(response_time, 4, 5)) / 60 + 
               as.numeric(substr(response_time, 7, 8)) / 3600, 
  priority_number = as.numeric(str_extract(priority, "\\d+"))
  ) %>%
  left_join(df_sun_clean, by = "date") %>%
  filter(hour_dec >= sunset & hour_dec < night)

calls_sorted_night <- calls_night %>%
  select(date, starts_with("calls_"), priority_number) %>%
  group_by(date) %>%
  summarise(
    across(starts_with("calls_"), \(x) sum(x, na.rm = TRUE)),
    across(starts_with("calls_disposition"), \(x) sum(x, na.rm = TRUE) / n()),
    calls_average_priority = mean(priority_number, na.rm = TRUE)
  ) %>%
  ungroup()

dst_rd_spring <- calls_sorted_night %>%
  mutate( 
    year = year(date)
    ) %>%
  left_join(dst_dates, by = "year") %>%
  mutate(days_until_spring = as.integer(date - dst_spring)) %>%
  filter(days_until_spring %in% -21:21) %>%
  mutate(
    dst_on = if_else(days_until_spring >= 0, "yes", "no")
  ) %>%
  group_by(days_until_spring, dst_on) %>%
  summarise(
    across(starts_with("calls_"), \(x) mean(x, na.rm = TRUE)),
    across(starts_with("calls_disposition"), \(x) mean(x, na.rm = TRUE)),
    calls_average_priority = mean(calls_average_priority, na.rm = TRUE)
  ) %>%
  ungroup()

vnames <- dst_rd_spring %>% select(starts_with("calls_")) %>% names()


for(X in vnames){ 

  f1 <- as.formula(paste0(X, "~ poly(days_until_spring, 2)")) 
  sub_no  <- dst_rd_spring %>% filter(dst_on == "no")
  sub_yes <- dst_rd_spring %>% filter(dst_on == "yes")

  if(length(unique(sub_no$days_until_spring)) < 3 | length(unique(sub_yes$days_until_spring)) < 3) next

  lm1 <- lm(f1, data = sub_no)
  lm2 <- lm(f1, data = sub_yes)
  pred1 <- predict(lm1, newdata = sub_no, se = TRUE)
  pred2 <- predict(lm2, newdata = sub_yes, se = TRUE)

  dst_rd_spring_plot <- bind_rows(sub_no, sub_yes) %>%
    mutate(pred = c(pred1$fit, pred2$fit), 
           upper = c(pred1$fit, pred2$fit) - qnorm(0.975)*c(pred1$se.fit, pred2$se.fit), 
           lower = c(pred1$fit, pred2$fit) + qnorm(0.975)*c(pred1$se.fit, pred2$se.fit)) 

  clean_title <- X %>% 
    str_replace("calls_", "") %>% 
    str_replace("_", " ") %>% 
    str_to_title()
  
  ylabel <- ifelse(str_detect(X, "clearedrate"), "Clearance rate", "Crimes") 
  
p <- ggplot(dst_rd_spring_plot, aes(x = days_until_spring, y = .data[[X]])) + 
    geom_point(aes(group = dst_on), size = 3, color = "royalblue", shape = 1) + 
    geom_line(aes(y = pred, group = dst_on)) + 
    geom_line(aes(y = upper, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_line(aes(y = lower, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_vline(xintercept = -0.5, linetype = "dashed", linewidth = 0.5) +  
    labs(title = paste("San Francisco 911 RD:", clean_title), 
         x = "Days until Spring DST starts", 
         y = ylabel)
print(p)
}

```



```{r, fig.width = 10}
#Fall RD (change disposition from raw count of crimes to proportion)
plottheme <- theme( 
  axis.text.x = element_text(size = 15), 
  axis.text.y = element_text(size = 15), 
  axis.title.x = element_text(size = 20), 
  axis.title.y = element_text(size = 20), 
  strip.text.x = element_text(size = 12), 
  strip.background = element_rect(fill = "grey85", color = "black"), 
  panel.background = element_blank(),  
  axis.line = element_line(colour = "black"), 
  legend.key = element_rect(colour = "transparent", fill = "transparent"), 
  legend.key.width = unit(2, "cm"), 
  legend.text = element_text(size = 20), 
  legend.title = element_text(size = 20), 
  legend.position = "none", 
  rect = element_rect(fill = "transparent")
  )


dst_dates <- tibble(
  year = 2015:2025,
  dst_spring = as.Date(c("2015-03-08", "2016-03-13", "2017-03-12", "2018-03-11", "2019-03-10", "2020-03-08", "2021-03-14", "2022-03-13", "2023-03-12", "2024-03-10", "2025-03-09")),
  dst_fall = as.Date(c("2015-11-01", "2016-11-06", "2017-11-05", "2018-11-04", "2019-11-03", "2020-11-01", "2021-11-07", "2022-11-06", "2023-11-05", "2024-11-03", "2025-11-02"))
)



df_sun_clean <- df_sun %>% distinct(date, .keep_all = TRUE)

calls_night <- calls_sorted %>%
  mutate(
  hour_dec = as.numeric(substr(response_time, 1, 2)) + 
               as.numeric(substr(response_time, 4, 5)) / 60 + 
               as.numeric(substr(response_time, 7, 8)) / 3600, 
  priority_number = as.numeric(str_extract(priority, "\\d+"))
  ) %>%
  left_join(df_sun_clean, by = "date") %>%
  filter(hour_dec >= sunset & hour_dec < night)

calls_sorted_night <- calls_night %>%
  select(date, starts_with("calls_"), priority_number) %>%
  group_by(date) %>%
  summarise(
    across(starts_with("calls_"), \(x) sum(x, na.rm = TRUE)),
    across(starts_with("calls_disposition"), \(x) sum(x, na.rm = TRUE) / n()),
    calls_average_priority = mean(priority_number, na.rm = TRUE)
  ) %>%
  ungroup()

dst_rd_fall <- calls_sorted_night %>%
  mutate( 
    year = year(date)
    ) %>%
  left_join(dst_dates, by = "year") %>%
  mutate(days_until_fall = as.integer(date - dst_fall)) %>%
  filter(days_until_fall %in% -21:21) %>%
  mutate(
    dst_on = if_else(days_until_fall >= 0, "yes", "no")
  ) %>%
  group_by(days_until_fall, dst_on) %>%
  summarise(
    across(starts_with("calls_"), \(x) mean(x, na.rm = TRUE)),
    across(starts_with("calls_disposition"), \(x) mean(x, na.rm = TRUE)),
    calls_average_priority = mean(calls_average_priority, na.rm = TRUE)
  ) %>%
  ungroup()

vnames <- dst_rd_fall %>% select(starts_with("calls_")) %>% names()


for(X in vnames){ 

  f1 <- as.formula(paste0(X, "~ poly(days_until_fall, 2)")) 
  sub_no  <- dst_rd_fall %>% filter(dst_on == "no")
  sub_yes <- dst_rd_fall %>% filter(dst_on == "yes")

  if(length(unique(sub_no$days_until_fall)) < 3 | length(unique(sub_yes$days_until_fall)) < 3) next

  lm1 <- lm(f1, data = sub_no)
  lm2 <- lm(f1, data = sub_yes)
  pred1 <- predict(lm1, newdata = sub_no, se = TRUE)
  pred2 <- predict(lm2, newdata = sub_yes, se = TRUE)

  dst_rd_fall_plot <- bind_rows(sub_no, sub_yes) %>%
    mutate(pred = c(pred1$fit, pred2$fit), 
           upper = c(pred1$fit, pred2$fit) - qnorm(0.975)*c(pred1$se.fit, pred2$se.fit), 
           lower = c(pred1$fit, pred2$fit) + qnorm(0.975)*c(pred1$se.fit, pred2$se.fit)) 

  clean_title <- X %>% 
    str_replace("calls_", "") %>% 
    str_replace("_", " ") %>% 
    str_to_title()
  
  ylabel <- ifelse(str_detect(X, "clearedrate"), "Clearance rate", "Crimes") 
  
p <- ggplot(dst_rd_fall_plot, aes(x = days_until_fall, y = .data[[X]])) + 
    geom_point(aes(group = dst_on), size = 3, color = "royalblue", shape = 1) + 
    geom_line(aes(y = pred, group = dst_on)) + 
    geom_line(aes(y = upper, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_line(aes(y = lower, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_vline(xintercept = -0.5, linetype = "dashed", linewidth = 0.5) +  
    labs(title = paste("San Francisco 911 RD:", clean_title), 
         x = "Days until Fall DST starts", 
         y = ylabel)
print(p)
}
```



