---
title: "Austin Crime RD"
output: 
  html_notebook:
    code_folding: hide
date: "2026-08-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("suncalc")
#install.packages("lutz")
library(tidyverse)
library(mosaic)
library(data.table)
library(lubridate)
library(suncalc)
library(lutz)
```


```{r, include=FALSE}

crime <- fread("../Data/raw/Austin/Crime_Reports1.csv")
```


```{r, warning = FALSE}
crime_sorted <- crime %>%
  mutate(
   
    occurred_date = lubridate::mdy(`Occurred Date`),
    report_date   = lubridate::mdy(`Report Date`),
    

    occurred_time = sprintf("%04d", `Occurred Time`) %>% 
                    sub("^(\\d{2})(\\d{2})$", "\\1:\\2:00", .),
    
    datetime = lubridate::ymd_hms(paste(occurred_date, occurred_time)),
    date = as.Date(datetime),
    year = year(datetime),
    month = lubridate::floor_date(datetime, "month"),
    day_of_week = lubridate::wday(datetime, week_start = 1),
    hour = hour(datetime), 
    minute = minute(datetime),
    
    offense = `Highest Offense Code`,
   description = `Highest Offense Description`,
         crime_robbery = ifelse(offense %in% c(300,302,303,305), 1, 0),
         crime_aggravated_assault = ifelse(offense %in% c(402,403,405,406,410,411), 1, 0),
         crime_burglary = ifelse(offense %in% c(500,502,504), 1, 0),
         crime_theft = ifelse(offense %in% c(600:610,612:621), 1, 0),
         crime_mv_theft = ifelse(offense %in% c(700), 1, 0), 
         crime_gun = ifelse(offense %in% c(1500, 1503, 1504, 1509, 2408, 2409, 2410, 1502), 1, 0),
         crime_disorder = ifelse(description %in% c("FAMILY DISTURBANCE",
  "DISTURBANCE - OTHER","FAMILY DISTURBANCE/PARENTAL", "DATING DISTURBANCE", "VOCO - ALCOHOL  CONSUMPTION", "VOCO SOLICITATION PROHIBIT", "VIOL CITY ORDINANCE - CURFEW", "CAMPING IN PARK","DOC FIGHTING", "POSSESSION OF MARIJUANA","POSS CONTROLLED SUB/NARCOTIC", "POSS OF DRUG PARAPHERNALIA", "DEL CONTROLLED SUB/NARCOTIC", "CRIMINAL MISCHIEF","GRAFFITI", "DAMAGE CITY PROP"), 1, 0),
         crime_violent = crime_robbery + crime_aggravated_assault,
            crime_property = crime_burglary + crime_theft + crime_mv_theft,
            crime_index = crime_violent + crime_property
    
  )
  
  
```

```{r}
calls <- fread("../Data/raw/Austin/APD_Computer_Aided_Dispatch_Incidents.csv")

names(calls) [6] <- "response_datetime" 
names(calls) [11] <- "arrived_datetime"
names(calls) [12] <- "closed_datetime"


calls <- calls %>%
  mutate(response_time = str_sub(response_datetime,12,23),
         response_date = str_sub(response_datetime,1,11),
         arrived_time = str_sub(arrived_datetime,12,23),
         arrived_date = str_sub(arrived_datetime,1,11),
         closed_time = str_sub(closed_datetime,12,23),
         closed_date = str_sub(closed_datetime,1,11),
         response_dt_parsed = lubridate::mdy_hms(response_datetime),
         year = lubridate::year(response_dt_parsed),
          month = lubridate::floor_date(response_dt_parsed, "month"),
         day_of_week = lubridate::wday(response_dt_parsed, week_start = 1),
         hour = lubridate::hour(response_dt_parsed),
         minute = lubridate::minute(response_dt_parsed)
         )




calls_sorted <- calls %>%
  mutate(
    disposition = case_when(
        `Call Disposition Description` %in% c("No Report", "Report Written", "Unable To Locate", "False Alarm", "Supplement     Written", "Non-Police Matter", "Report Written MH", "Reassigned call", "District Representatives", "No Report MH") ~ `Call Disposition Description`,
      TRUE ~ NA_character_),
    priority = `Priority Level`,
    priority_number = as.numeric(str_extract(priority, "\\d+")),
    disposition_clean = str_trim(toupper(disposition)),
    
    calls_disorder = as.integer(`Initial Problem Category` %in% c("Disturbance", "Disorderly Conduct", "Property Damage/Vandalism", "Drugs", "Prositution")),
    calls_behavior = as.integer(`Initial Problem Category` %in% c("Suspicious Things", "Trespassing")),
    calls_traffic = as.integer(`Initial Problem Category` == "Crashes"),
    calls_gun = as.integer(`Initial Problem Category` %in% c("Shoot/Stab", "Weapons/Firearms Violations")),
         
        calls_robbery = as.integer(`Initial Problem Category` == "Robbery"),
        calls_aggravated_assault = as.integer(`Initial Problem Category` == "Aggravated Assault"),
        calls_burglary = as.integer(`Initial Problem Category` == "Burglary"),
        calls_theft = as.integer(`Initial Problem Category` == "Theft"),
        calls_mv_theft = as.integer(`Initial Problem Category` == "Auto Theft"),
  
            calls_violent = calls_robbery + calls_aggravated_assault,
            calls_property = calls_burglary + calls_theft + calls_mv_theft,
            calls_index = calls_violent + calls_property,
    
              initiator = case_when(
                `Incident Type` == "Officer-Initiated Incident" ~ "Officer",
                `Incident Type` == "Dispatched Incident" ~ "Citizen",
                TRUE ~ NA_character_
              )
              )
```


```{r, fig.width=10}
by_minute <- crime_sorted %>%
   filter(year %in% 2012:2024) %>%
  count(minute = minute)

ggplot(by_minute, aes(minute, n)) +
  geom_line() + 
  scale_x_continuous(breaks = seq(0, 59, by = 3)) +
  labs(title = "Austin Reported Times by Minute of the Hour", x = "Minute", y = "Calls") +
  theme_minimal()
```

```{r, fig.width=10}
by_minute <- crime_sorted %>%
  filter(year %in% 2012:2024) %>%
  count(minute = minute, year)

ggplot(by_minute, aes(minute, n)) +
  geom_line() + 
  facet_wrap(~year, scale = "free_y") +
  scale_x_continuous(breaks = seq(0, 59, by = 10)) +
   labs(title = "Austin Reported Times by Minute of the Hour", x = "Minute", y = "Calls") +
  theme_minimal()
```

```{r, fig.width=10}
by_minute_month <- crime_sorted %>%
   filter(year %in% 2012:2024) %>%
  mutate(month_clean = lubridate::month(month, label = TRUE)) %>%
  count(month_clean, minute)

ggplot(by_minute_month, aes(minute, n)) +
  geom_line() + 
  facet_wrap(~month_clean, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 59, by = 15)) +
  labs(title = "Austin Reported Times by Minute of the Hour", x = "Minute", y = "Calls") +
  theme_minimal() 
```

```{r, fig.width=10}
#hr of day

crime_by_hour <- crime_sorted %>%
   filter(year %in% 2012:2024) %>%
  count(hour = hour) %>%
  mutate(source = "Crime Reports")

calls_by_hour <- calls_sorted %>%
   filter(year %in% 2012:2024) %>%
  count(hour = hour) %>%
  mutate(source = "Calls for Service")

by_hour_combined <- bind_rows(crime_by_hour, calls_by_hour)

ggplot(by_hour_combined, aes(hour, n, color = source)) +
  geom_line() + 
  scale_x_continuous(breaks = 0:24) +
  labs(title = "Austin Reported Times by Hour of the Day", x = "Hour", y = "Calls") +
  theme_minimal()

```

```{r, fig.width = 10, warning = FALSE}
gc()
rm(crime_by_hour, calls_by_hour, by_hour_combined, by_minute_month, by_minute)

crime_sorted_yr <- crime_sorted %>% filter(year %in% 2012:2024)

crime_by_hour_type <- bind_rows(
  crime_sorted_yr %>% filter(crime_robbery == 1) %>% count(hour = hour) %>% mutate(type = "Robbery"),
  crime_sorted_yr %>% filter(crime_aggravated_assault == 1) %>% count(hour = hour) %>% mutate(type = "Aggravated Assault"),
  crime_sorted_yr %>% filter(crime_burglary == 1) %>% count(hour = hour) %>% mutate(type = "Burglary"),
  crime_sorted_yr %>% filter(crime_theft == 1) %>% count(hour = hour) %>% mutate(type = "Theft"),
  crime_sorted_yr %>% filter(crime_mv_theft == 1) %>% count(hour = hour) %>% mutate(type = "MV Theft"),
  crime_sorted_yr %>% filter(crime_disorder == 1) %>% count(hour = hour) %>% mutate(type = "Disorder"),
  crime_sorted_yr %>% filter(crime_gun == 1) %>% count(hour = hour) %>% mutate(type = "Gunshots"),
  crime_sorted_yr %>% filter(crime_violent == 1) %>% count(hour = hour) %>% mutate(type = "Violent Crime"),
  crime_sorted_yr %>% filter(crime_property == 1) %>% count(hour = hour) %>% mutate(type = "Property Crime")
) %>%
  mutate(source = "Crime Reports")

calls_sorted_yr <- calls_sorted %>% filter(year %in% 2012:2024)

calls_by_hour_type <- bind_rows(
  calls_sorted_yr %>% filter(calls_robbery == 1) %>% count(hour = hour) %>% mutate(type = "Robbery"),
  calls_sorted_yr %>% filter(calls_aggravated_assault == 1) %>% count(hour = hour) %>% mutate(type = "Aggravated Assault"),
  calls_sorted_yr %>% filter(calls_burglary == 1) %>% count(hour = hour) %>% mutate(type = "Burglary"),
  calls_sorted_yr %>% filter(calls_theft == 1) %>% count(hour = hour) %>% mutate(type = "Theft"),
  calls_sorted_yr %>% filter(calls_mv_theft == 1) %>% count(hour = hour) %>% mutate(type = "MV Theft"),
  calls_sorted_yr %>% filter(calls_disorder == 1) %>% count(hour = hour) %>% mutate(type = "Disorder"),
  calls_sorted_yr %>% filter(calls_gun == 1) %>% count(hour = hour) %>% mutate(type = "Gunshots"),
  calls_sorted_yr %>% filter(calls_violent == 1) %>% count(hour = hour) %>% mutate(type = "Violent Crime"),
  calls_sorted_yr %>% filter(calls_property == 1) %>% count(hour = hour) %>% mutate(type = "Property Crime")
) %>%
  mutate(source = "Calls for Service")

by_hour_type_combined <- bind_rows(crime_by_hour_type, calls_by_hour_type)

# graphed distribution of 911 times by hour
ggplot(by_hour_type_combined, aes(hour, n, color = source)) +
  geom_line() +
  facet_wrap(~type, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 24, by = 4)) +
  labs(title = "Austin Reported Times by Hour of the Day and Call Type",
       x = "Hour", y = "Calls", color = "Source") +
  theme_minimal()
```

```{r, fig.width= 10}
by_day_week <- crime_sorted %>% 
   filter(year %in% 2012:2024) %>%
  count(day = day_of_week)


  
# graph of distribution of 911 times by hour
ggplot(by_day_week, aes(day, n, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Austin Reported by Day of the Week", x = "Day", y = "Calls") +
  theme_minimal()
```

```{r, fig.width = 10, warning = FALSE}
#day of week type

by_week_type <- crime_sorted %>% filter(year %in% 2012:2024) %>% 
  bind_rows(
  crime_sorted %>% filter(crime_robbery == 1) %>% count(day = day_of_week) %>% mutate(type = "Robbery"),
  crime_sorted %>% filter(crime_aggravated_assault == 1) %>% count(day = day_of_week) %>% mutate(type = "Aggravated Assault"),
  crime_sorted %>% filter(crime_burglary == 1) %>% count(day = day_of_week) %>% mutate(type = "Burglary"),
  crime_sorted %>% filter(crime_theft == 1) %>% count(day = day_of_week) %>% mutate(type = "Theft"), 
  crime_sorted %>% filter(crime_mv_theft == 1) %>% count(day = day_of_week) %>% mutate(type = "MV Theft"),
  crime_sorted %>% filter(crime_disorder == 1) %>% count(day = day_of_week) %>% mutate(type = "Disorder"),
  crime_sorted %>% filter(crime_gun == 1) %>% count(day = day_of_week) %>% mutate(type = "Gunshots"),
  crime_sorted %>% filter(crime_violent == 1) %>% count(day = day_of_week) %>% mutate(type = "Violent Crime"),
  crime_sorted %>% filter(crime_property == 1) %>% count(day = day_of_week) %>% mutate(type = "Property Crime")
)


  
  ggplot(by_week_type, aes(day, n, color = type, group = type)) +
  geom_line() +
  geom_point() +
  facet_wrap(~type, scales = "free_y") +
  labs(title = "Austin Reported by Day of the Week and Type", x = "Day", y = "Calls") +
  theme_minimal()
```

```{r, fig.width = 10}
#day/year

by_date <- crime_sorted %>% 
   filter(year %in% 2012:2024) %>%
  count(date = date)

ggplot(by_date, aes(date, n)) +
  geom_line(alpha = .7) + 
  scale_x_date(date_labels = "%b-%d-%y", date_breaks = "6 months") +
  labs(title = "Austin Reported Times by Day Timeline", x = "Date", y = "Calls") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) 
```

```{r, fig.width = 10, warning = FALSE}
#day/year type

by_day_type <- crime_sorted %>% filter(year %in% 2012:2024) %>% 
  bind_rows(
  crime_sorted %>% filter(crime_robbery == 1) %>% count(day = date) %>% mutate(type = "Robbery"),
  crime_sorted %>% filter(crime_aggravated_assault == 1) %>% count(day = date) %>% mutate(type = "Aggravated Assault"),
  crime_sorted %>% filter(crime_burglary == 1) %>% count(day = date) %>% mutate(type = "Burglary"),
  crime_sorted %>% filter(crime_theft == 1) %>% count(day= date) %>% mutate(type = "Theft"), 
  crime_sorted %>% filter(crime_mv_theft == 1) %>% count(day = date) %>% mutate(type = "MV Theft"),
  crime_sorted %>% filter(crime_disorder == 1) %>% count(day = date) %>% mutate(type = "Disorder"),
  crime_sorted %>% filter(crime_gun == 1) %>% count(day = date) %>% mutate(type = "Gunshots"),
  crime_sorted %>% filter(crime_violent == 1) %>% count(day = date) %>% mutate(type = "Violent Crime"),
  crime_sorted %>% filter(crime_property == 1) %>% count(day = date) %>% mutate(type = "Property Crime")
)

  
ggplot(by_day_type, aes(day, n, color = type, group = type)) +
  geom_line(alpha = .7) +
  geom_smooth(se = FALSE) +
  facet_wrap(~type, scales = "free_y") +
  labs(title = "Austin Report by Timeline and Type", x = "Day", y = "Calls") +
  theme_minimal() +
   theme(axis.text.x = element_text(angle = 45))
```

```{r, fig.width = 10, warning = FALSE}
#month/year

rm(by_day_type, by_date, by_week, by_week_type)



crime_by_month <- crime_sorted %>% 
  filter(year %in% 2012:2024) %>%
      count(month) %>%
  mutate(source = "Crime Reports")
  
calls_by_month <- calls_sorted %>%
   filter(year %in% 2012:2024) %>%
  count(month = month) %>%
  mutate(source = "Calls for Service")

by_month_combine <- bind_rows(crime_by_month, calls_by_month)
      
ggplot(by_month_combine, aes(month, n, color = source)) +
  geom_line()  +
  labs(title = "Austin Report by Month", x = "Month", y = "Calls") +
    theme_minimal ()
```

```{r, fig.width = 10, warning=FALSE}
#month/year type


crime_sorted_yr <- crime_sorted %>% filter(year %in% 2012:2024)

crime_by_month_type <- bind_rows(
  crime_sorted_yr%>% filter(crime_robbery == 1) %>% count(month = month) %>% mutate(type = "Robbery"),
  crime_sorted_yr%>% filter(crime_aggravated_assault == 1) %>% count(month = month) %>% mutate(type = "Aggravated Assault"),
  crime_sorted_yr%>% filter(crime_burglary == 1) %>% count(month = month) %>% mutate(type = "Burglary"),
  crime_sorted_yr%>% filter(crime_theft == 1) %>% count(month = month) %>% mutate(type = "Theft"), 
  crime_sorted_yr%>% filter(crime_mv_theft == 1) %>% count(month = month) %>% mutate(type = "MV Theft"),
  crime_sorted_yr%>% filter(crime_disorder == 1) %>% count(month = month) %>% mutate(type = "Disorder"),
  crime_sorted_yr%>% filter(crime_gun == 1) %>% count(month = month) %>% mutate(type = "Gunshots"),
  crime_sorted_yr%>% filter(crime_violent == 1) %>% count(month = month) %>% mutate(type = "Violent Crime"),
  crime_sorted_yr%>% filter(crime_property == 1) %>% count(month = month) %>% mutate(type = "Property Crime")
) %>%
  mutate(source = "Crime Reports")


calls_sorted_yr <- calls_sorted %>% filter(year %in% 2012:2024)

calls_by_month_type <- bind_rows(
  calls_sorted_yr %>% filter(calls_robbery == 1) %>% count(month = month) %>% mutate(type = "Robbery"),
  calls_sorted_yr %>% filter(calls_aggravated_assault == 1) %>% count(month = month) %>% mutate(type = "Aggravated Assault"),
  calls_sorted_yr %>% filter(calls_burglary == 1) %>% count(month = month) %>% mutate(type = "Burglary"),
  calls_sorted_yr %>% filter(calls_theft == 1) %>% count(month = month) %>% mutate(type = "Theft"),
  calls_sorted_yr %>% filter(calls_mv_theft == 1) %>% count(month = month) %>% mutate(type = "MV Theft"),
  calls_sorted_yr %>% filter(calls_disorder == 1) %>% count(month = month) %>% mutate(type = "Disorder"),
  calls_sorted_yr %>% filter(calls_gun == 1) %>% count(month = month) %>% mutate(type = "Gunshots"),
  calls_sorted_yr %>% filter(calls_violent == 1) %>% count(month = month) %>% mutate(type = "Violent Crime"),
  calls_sorted_yr %>% filter(calls_property == 1) %>% count(month = month) %>% mutate(type = "Property Crime")
) %>%
  mutate(source = "Calls for Service")

by_month_type_combined <- bind_rows(crime_by_month_type, calls_by_month_type)


ggplot(by_month_type_combined, aes(month, n, color = source)) +
  geom_line(alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_wrap(~type, scales = "free_y") +
  labs(title = "Austin Reported by Month and Type", x = "Month", y = "Calls*") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45))
```

```{r, fig.width = 10, warning=FALSE}
#heatmap percent 

heatmap_by_type <- crime_sorted %>% filter(year %in% 2012:2024) %>%
  bind_rows(
  crime_sorted %>% filter(crime_robbery == 1) %>% count(day_of_week, hour) %>% mutate(type = "Robbery"),
  crime_sorted %>% filter(crime_aggravated_assault == 1) %>% count(day_of_week, hour) %>% mutate(type = "Aggravated Assault"),
  crime_sorted %>% filter(crime_burglary == 1) %>% count(day_of_week, hour) %>% mutate(type = "Burglary"),
  crime_sorted %>% filter(crime_theft == 1) %>% count(day_of_week, hour) %>% mutate(type = "Theft"), 
  crime_sorted %>% filter(crime_mv_theft == 1) %>% count(day_of_week, hour) %>% mutate(type = "MV Theft"),
  crime_sorted %>% filter(crime_disorder == 1) %>% count(day_of_week, hour) %>% mutate(type = "Disorder"),
  crime_sorted %>% filter(crime_gun == 1) %>% count(day_of_week, hour) %>% mutate(type = "Gunshots")
)

heatmap_by_type_percent <- heatmap_by_type %>%
  group_by(type) %>%
  mutate(percent = (n / sum(n)) * 100) %>%
  ungroup()

ggplot(heatmap_by_type_percent, aes(hour, day_of_week, fill = percent)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "magma") +
  scale_x_continuous(breaks = seq(0, 23, by = 4)) +
  facet_wrap(~type, scales = "free") +
  theme_minimal() +
   labs(title = "Austin Reported Volume Heatmap by Day and Hour", x = "Hour of Day", y = "Day of Week", fill = "% of Types Total") 
```

```{r, include=FALSE}
#Information needed 


df_dates <- expand.grid(year = 2012:2024, month = 1:12, day = 1:31) %>% 

  filter(complete.cases(ymd(paste(year, month, day)))) %>% 

  mutate(date = ymd(paste(year, month, day, sep = "-"))) %>% 

  arrange(date) 

 df_dates

#Get suntime data 


df_sun <- df_dates %>% 

  mutate(lat = 30.267118,  

         lon = -97.743130) %>% 

  getSunlightTimes(data = ., tz = "America/Chicago", keep = c("dawn", "sunrise", "sunset", "dusk", "night")) %>% 

  rename_all(tolower) %>%
  mutate(
    dawn = hour(dawn) + minute(dawn) / 60,
    sunrise = hour(sunrise) + minute(sunrise) / 60,
    sunset = hour(sunset) + minute(sunset) / 60,
    dusk = hour(dusk) + minute(dusk) / 60,
    night = hour(night) + minute(night) / 60
  )

df_sun

```

```{r, fig.width = 10}
#sun graph
df_sun %>%
  filter(year(date) == 2024) %>%
  ggplot() +
    geom_area(aes(x = date, y = dusk), fill = "skyblue3") +  
    geom_area(aes(x = date, y = sunset), fill = "khaki1") +  
    geom_area(aes(x = date, y = sunrise), fill = "skyblue3") +  
    geom_area(aes(x = date, y = dawn), fill = "grey90") +  
      scale_y_continuous(breaks = seq(0, 23, 2), expand = c(0, 0)) +  
      scale_x_date(date_labels =  "%b", date_breaks = "1 month", expand = c(0,0)) + 
      coord_cartesian(ylim = c(0, 23)) +  
      labs(x = "Month of 2024", y = "Time of the day") +  
      theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        panel.background = element_rect(fill = "grey90"),   
        panel.grid = element_blank(),  
        panel.border = element_blank(),   
        rect = element_blank(),  
        axis.line = element_blank()
        )  

```

```{r, fig.width = 10}
dst_dates <- tibble(
  year = 2012:2024,
  dst_spring = as.Date(c("2012-03-11", "2013-03-10", "2014-03-09", "2015-03-08", "2016-03-13", "2017-03-12", "2018-03-11", "2019-03-10", "2020-03-08", "2021-03-14", "2022-03-13", "2023-03-12", "2024-03-10")),
  dst_fall = as.Date(c("2012-11-04", "2013-11-03", "2014-11-02", "2015-11-01", "2016-11-06", "2017-11-05", "2018-11-04", "2019-11-03", "2020-11-01", "2021-11-07", "2022-11-06", "2023-11-05", "2024-11-03"))
)

plottheme <- theme( 
  axis.text.x = element_text(size = 15), 
  axis.text.y = element_text(size = 15), 
  axis.title.x = element_text(size = 20), 
  axis.title.y = element_text(size = 20), 
  strip.text.x = element_text(size = 12), 
  strip.background = element_rect(fill = "grey85", color = "black"), 
  panel.background = element_blank(),  
  axis.line = element_line(colour = "black"), 
  legend.key = element_rect(colour = "transparent", fill = "transparent"), 
  legend.key.width = unit(2, "cm"), 
  legend.text = element_text(size = 20), 
  legend.title = element_text(size = 20), 
  legend.position = "none", 
  rect = element_rect(fill = "transparent")
  )


crime_night <- crime_sorted %>%
  left_join(df_sun, by = "date") %>%
  filter(hour >= sunset & hour < night)

crime_sorted_night <- crime_night %>%
  group_by(date) %>%
  summarise(
    across(starts_with("crime_"), \(x) sum(x, na.rm = TRUE))
  ) %>%
  ungroup()

dst_rd_spring <- crime_sorted_night %>%
  mutate( 
    year = year(date)
    ) %>%
  left_join(dst_dates, by = "year") %>%
  mutate(days_until_spring = as.integer(date - dst_spring)) %>%
  filter(days_until_spring %in% -21:21) %>%
  mutate(
    dst_on = if_else(days_until_spring >= 0, "yes", "no")
  ) %>%
  group_by(days_until_spring, dst_on) %>%
  summarise(
    across(starts_with("crime_"), \(x) mean(x, na.rm = TRUE))
  ) %>%
  ungroup()

vnames <- dst_rd_spring %>% select(starts_with("crime_")) %>% names()


for(X in vnames){ 

  f1 <- as.formula(paste0(X, "~ poly(days_until_spring, 2)")) 
  sub_no  <- dst_rd_spring %>% filter(dst_on == "no")
  sub_yes <- dst_rd_spring %>% filter(dst_on == "yes")

  if(length(unique(sub_no$days_until_spring)) < 3 | length(unique(sub_yes$days_until_spring)) < 3) next

  lm1 <- lm(f1, data = sub_no)
  lm2 <- lm(f1, data = sub_yes)
  pred1 <- predict(lm1, newdata = sub_no, se = TRUE)
  pred2 <- predict(lm2, newdata = sub_yes, se = TRUE)

  dst_rd_spring_plot <- bind_rows(sub_no, sub_yes) %>%
    mutate(pred = c(pred1$fit, pred2$fit), 
           upper = c(pred1$fit, pred2$fit) - qnorm(0.975)*c(pred1$se.fit, pred2$se.fit), 
           lower = c(pred1$fit, pred2$fit) + qnorm(0.975)*c(pred1$se.fit, pred2$se.fit)) 

  clean_title <- X %>% 
    str_replace("crime_", "") %>% 
    str_replace("_", " ") %>% 
    str_to_title()
  
  ylabel <- ifelse(str_detect(X, "clearedrate"), "Clearance rate", "Crimes") 
  
p <- ggplot(dst_rd_spring_plot, aes(x = days_until_spring, y = .data[[X]])) + 
    geom_point(aes(group = dst_on), size = 3, color = "royalblue", shape = 1) + 
    geom_line(aes(y = pred, group = dst_on)) + 
    geom_line(aes(y = upper, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_line(aes(y = lower, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_vline(xintercept = -0.5, linetype = "dashed", linewidth = 0.5) +  
    labs(title = paste("Austin Reported RD:", clean_title), 
         x = "Days until Spring DST starts", 
         y = ylabel)
print(p)
}


```



```{r, fig.width = 10}
dst_dates <- tibble(
  year = 2012:2024,
  dst_spring = as.Date(c("2012-03-11", "2013-03-10", "2014-03-09", "2015-03-08", "2016-03-13", "2017-03-12", "2018-03-11", "2019-03-10", "2020-03-08", "2021-03-14", "2022-03-13", "2023-03-12", "2024-03-10")),
  dst_fall = as.Date(c("2012-11-04", "2013-11-03", "2014-11-02", "2015-11-01", "2016-11-06", "2017-11-05", "2018-11-04", "2019-11-03", "2020-11-01", "2021-11-07", "2022-11-06", "2023-11-05", "2024-11-03"))
)

plottheme <- theme( 
  axis.text.x = element_text(size = 15), 
  axis.text.y = element_text(size = 15), 
  axis.title.x = element_text(size = 20), 
  axis.title.y = element_text(size = 20), 
  strip.text.x = element_text(size = 12), 
  strip.background = element_rect(fill = "grey85", color = "black"), 
  panel.background = element_blank(),  
  axis.line = element_line(colour = "black"), 
  legend.key = element_rect(colour = "transparent", fill = "transparent"), 
  legend.key.width = unit(2, "cm"), 
  legend.text = element_text(size = 20), 
  legend.title = element_text(size = 20), 
  legend.position = "none", 
  rect = element_rect(fill = "transparent")
  )


crime_night <- crime_sorted %>%
  left_join(df_sun, by = "date") %>%
  filter(hour >= sunset & hour < night)

crime_sorted_night <- crime_night %>%
  group_by(date) %>%
  summarise(
    across(starts_with("crime_"), \(x) sum(x, na.rm = TRUE))
  ) %>%
  ungroup()

dst_rd_fall <- crime_sorted_night %>%
  mutate( 
    year = year(date)
    ) %>%
  left_join(dst_dates, by = "year") %>%
  mutate(days_until_fall = as.integer(date - dst_fall)) %>%
  filter(days_until_fall %in% -21:21) %>%
  mutate(
    dst_on = if_else(days_until_fall >= 0, "yes", "no")
  ) %>%
  group_by(days_until_fall, dst_on) %>%
  summarise(
    across(starts_with("crime_"), \(x) mean(x, na.rm = TRUE))
  ) %>%
  ungroup()

vnames <- dst_rd_fall %>% select(starts_with("crime_")) %>% names()


for(X in vnames){ 

  f1 <- as.formula(paste0(X, "~ poly(days_until_fall, 2)")) 
  sub_no  <- dst_rd_fall %>% filter(dst_on == "no")
  sub_yes <- dst_rd_fall %>% filter(dst_on == "yes")

  if(length(unique(sub_no$days_until_fall)) < 3 | length(unique(sub_yes$days_until_fall)) < 3) next

  lm1 <- lm(f1, data = sub_no)
  lm2 <- lm(f1, data = sub_yes)
  pred1 <- predict(lm1, newdata = sub_no, se = TRUE)
  pred2 <- predict(lm2, newdata = sub_yes, se = TRUE)

  dst_rd_fall_plot <- bind_rows(sub_no, sub_yes) %>%
    mutate(pred = c(pred1$fit, pred2$fit), 
           upper = c(pred1$fit, pred2$fit) - qnorm(0.975)*c(pred1$se.fit, pred2$se.fit), 
           lower = c(pred1$fit, pred2$fit) + qnorm(0.975)*c(pred1$se.fit, pred2$se.fit)) 

  clean_title <- X %>% 
    str_replace("crime_", "") %>% 
    str_replace("_", " ") %>% 
    str_to_title()
  
  ylabel <- ifelse(str_detect(X, "clearedrate"), "Clearance rate", "Crimes") 
  
p <- ggplot(dst_rd_fall_plot, aes(x = days_until_fall, y = .data[[X]])) + 
    geom_point(aes(group = dst_on), size = 3, color = "royalblue", shape = 1) + 
    geom_line(aes(y = pred, group = dst_on)) + 
    geom_line(aes(y = upper, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_line(aes(y = lower, group = dst_on), linetype = "dashed", linewidth = 0.7, color = "grey80") + 
    geom_vline(xintercept = -0.5, linetype = "dashed", linewidth = 0.5) +  
    labs(title = paste("Austin Reported RD:", clean_title), 
         x = "Days until Fall DST starts", 
         y = ylabel)
print(p)
}


```
